### ISSUE TITLE
android build issue

### ISSUE THREAD

**Issue by waizui** [geekbrother/sqlcipher-amalgamation#1]
Hi thanks for your work.
I got error when I was build to android using NDK tools
something like  <b>"[arm64-v8a] Compile        : sqlite3 <= sqlite3.c
D:/Repos/SqlCipherAmalgation/src/jni/sqlite3.c:39210:42: error: use of undeclared identifier 'close'
  { "close",        (sqlite3_syscall_ptr)close,      0  }," </b> appeared . seems like the source file contains some compile errors.
I'm wondering if you have successfully build a lib using this amalgamation?

**Comment by geekbrother** [comment]
Hi @waizui !
The package is currently used in Android (npm package) and iOS (cocoapod) builds without issues. Did you use it as an npm package for ReactNative (and then eject and use Android Studio) or in another way?

**Comment by geekbrother** [comment]
Did you added `../../node_modules/sqlcipher-amalgamation/src` as includes in your CMakeFile ?

**Comment by geekbrother** [comment]
Closing as of no responses from the issuer.
